/*.$file${HSMs::../src::AlarmClock_SM.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: AlarmClock.qm
* File:  ${HSMs::../src::AlarmClock_SM.h}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${HSMs::../src::AlarmClock_SM.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef ALARM_CLOCK_H
#define ALARM_CLOCK_H

enum ClockAlarm_Settings{
    SET_SIG=Q_USER_SIG,
    OK_SIG,
    ABORT_SIG,
    ALARM_SIG,
    TICK_SIG,
    MAX_SIG
};
enum Time_Mode{
    MODE_24H,
    MODE_12H
};
enum Alarm_Status{
    ALARM_OFF,
    ALARM_ON
};
#define INITIAL_CURR_TIME    ((10UL * 3600UL * 10UL * 60UL * 10UL)*10UL)
#define INITIAL_ALARM_TIME   (8UL * 3600UL)
#define MAX_TIME    (864000UL)
#define TICKING_CURR_TIME_ROW    0
#define TICKING_CURR_TIME_COL    3
#define GET_HOUR(seconds)     (seconds/3600UL)
#define GET_MIN(seconds)      ((seconds/60UL)%60UL)
#define GET_SEC(seconds)      (seconds % 60UL)
#define DIGIT1(d)             (d/10U)
#define DIGIT2(d)             (d%10U)
/*.$declare${HSMs::AlarmClock_Ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${HSMs::AlarmClock_Ctor} ................................................*/
void AlarmClock_Ctor(void);
/*.$enddecl${HSMs::AlarmClock_Ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#endif